import { defineConfig } from 'vite'
import { sentryVitePlugin } from "@sentry/vite-plugin";
import { devtools } from '@tanstack/devtools-vite'
import viteReact from '@vitejs/plugin-react'
import { visualizer } from "rollup-plugin-visualizer";
import { tanstackRouter } from '@tanstack/router-plugin/vite'
import { fileURLToPath, URL } from 'node:url'
import tailwindcss from "@tailwindcss/vite"
import { readFileSync } from "node:fs";

const serverPackage = JSON.parse(
	readFileSync(fileURLToPath(new URL("../server/package.json", import.meta.url)), "utf8"),
) as { version: string };

// Environment favicon variants (generated by scripts/generate-favicons.ts).
// Production builds keep the clean /favicon.png from index.html.
const faviconByMode: Record<string, string> = {
  development: '/favicon-dev.png',
  staging: '/favicon-stage.png',
};

// Devtools packages to exclude from production builds
const devtoolsPackages = [
  '@tanstack/react-devtools',
  '@tanstack/react-query-devtools',
  '@tanstack/react-router-devtools',
  '@tanstack/react-ai-devtools',
  '@tanstack/ai-devtools-core',
];

// https://vite.dev/config/
export default defineConfig(({ mode }) => {
  const isProduction = mode === 'production';
  const shouldUploadSourceMaps = isProduction && Boolean(process.env.SENTRY_AUTH_TOKEN);
  const port = Number.parseInt(process.env.PORT ?? '3001', 10);
  
  return {
	define: {
		"import.meta.env.VITE_APP_VERSION": JSON.stringify(serverPackage.version),
	},
  build: {
    outDir: "dist",
    // Enable minification (esbuild is faster and produces good results)
    minify: 'esbuild',
    // Target modern browsers for smaller output
    target: 'esnext',
    rollupOptions: {
      output: {
        // Smarter chunk splitting strategy
        manualChunks(id) {
          // Monaco editor - large, lazy-loaded anyway
          if (id.includes('monaco-editor')) {
            return 'monaco-editor';
          }
          // Radix UI primitives - group all radix packages together
          if (id.includes('@radix-ui') || id.includes('node_modules/radix-ui')) {
            return 'radix-ui';
          }
          // Icons - lucide-react
          if (id.includes('lucide-react')) {
            return 'icons';
          }
          // TanStack libraries (excluding devtools)
          if (id.includes('@tanstack') && !devtoolsPackages.some(pkg => id.includes(pkg))) {
            return 'tanstack';
          }
          // React core
          if (id.includes('react-dom')) {
            return 'react-dom';
          }
          // Monitoring & analytics
          if (id.includes('@sentry') || id.includes('posthog')) {
            return 'monitoring';
          }
        },
      },
    },
		sourcemap: shouldUploadSourceMaps ? 'hidden' : false,
    // Increase chunk size warning limit (monaco is large but lazy-loaded)
    chunkSizeWarningLimit: 1000,
  },
  optimizeDeps: {
    // Include heavy deps that are needed immediately
    include: [
      'monaco-editor',
      'react',
      'react-dom',
      '@tanstack/react-query',
      '@tanstack/react-router',
      '@tanstack/ai-react',
      'lucide-react',
      'dayjs'
    ],
    // Exclude heavy deps from pre-bundling if not needed immediately
    exclude: [
      '@tanstack/react-query-devtools',
      '@tanstack/react-router-devtools',
      '@tanstack/react-ai-devtools',
    ],
  },
  plugins: [
    {
      name: 'env-favicon',
      transformIndexHtml(html: string) {
        const favicon = faviconByMode[mode];
        return favicon ? html.replace('/favicon.png', favicon) : html;
      },
    },
    tailwindcss(),
    devtools({ removeDevtoolsOnBuild: true }),
    tanstackRouter({
      target: 'react',
      autoCodeSplitting: true,
      disableLogging: true,
    }),
    viteReact(),
    visualizer({
      open: false, // Don't auto-open on every build
      gzipSize: true,
      brotliSize: true,
      filename: 'stats.html',
    }),
		...(shouldUploadSourceMaps
			? [
					sentryVitePlugin({
						authToken: process.env.SENTRY_AUTH_TOKEN,
						org: "husamql3",
						project: "db-studio-web",
						url: "https://de.sentry.io",
						release: { name: `db-studio@${serverPackage.version}` },
						sourcemaps: { filesToDeleteAfterUpload: "dist/**/*.map" },
						silent: true,
					}),
				]
			: []),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
      // Replace devtools with empty modules in production
      ...(isProduction ? Object.fromEntries(
        devtoolsPackages.map(pkg => [pkg, fileURLToPath(new URL('./src/lib/empty-module.ts', import.meta.url))])
      ) : {}),
    },
  },
  server: {
    port,
    host: true,
    proxy: {
      "/api": {
        target: process.env.VITE_API_PROXY_TARGET ?? 'https://api.db-studio.localhost',
        changeOrigin: true,
        secure: false,
        // No rewrite: the server owns the /api namespace, so forward the
        // prefix intact instead of stripping it. See db-studio#214.
      },
    },
  },
}})
