/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as PathlessLayoutIndexRouteImport } from './routes/_pathlessLayout/index'
import { Route as PathlessLayoutBrowserRouteImport } from './routes/_pathlessLayout/browser'
import { Route as PathlessLayoutIndexesRouteImport } from './routes/_pathlessLayout/indexes'
import { Route as PathlessLayoutLogsRouteImport } from './routes/_pathlessLayout/logs'
import { Route as PathlessLayoutVisualizerRouteImport } from './routes/_pathlessLayout/visualizer'
import { Route as PathlessLayoutRunnerIndexRouteImport } from './routes/_pathlessLayout/runner/index'
import { Route as PathlessLayoutRunnerQueryIdRouteImport } from './routes/_pathlessLayout/runner/$queryId'
import { Route as PathlessLayoutSchemaIndexRouteImport } from './routes/_pathlessLayout/schema/index'
import { Route as PathlessLayoutSchemaTableRouteImport } from './routes/_pathlessLayout/schema/$table'
import { Route as PathlessLayoutTableIndexRouteImport } from './routes/_pathlessLayout/table/index'
import { Route as PathlessLayoutTableTableRouteImport } from './routes/_pathlessLayout/table/$table'

const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutIndexRoute = PathlessLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PathlessLayoutRoute,
} as any)
const PathlessLayoutBrowserRoute = PathlessLayoutBrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => PathlessLayoutRoute,
} as any)
const PathlessLayoutIndexesRoute = PathlessLayoutIndexesRouteImport.update({
  id: '/indexes',
  path: '/indexes',
  getParentRoute: () => PathlessLayoutRoute,
} as any)
const PathlessLayoutLogsRoute = PathlessLayoutLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => PathlessLayoutRoute,
} as any)
const PathlessLayoutVisualizerRoute =
  PathlessLayoutVisualizerRouteImport.update({
    id: '/visualizer',
    path: '/visualizer',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutRunnerIndexRoute =
  PathlessLayoutRunnerIndexRouteImport.update({
    id: '/runner/',
    path: '/runner/',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutRunnerQueryIdRoute =
  PathlessLayoutRunnerQueryIdRouteImport.update({
    id: '/runner/$queryId',
    path: '/runner/$queryId',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutSchemaIndexRoute =
  PathlessLayoutSchemaIndexRouteImport.update({
    id: '/schema/',
    path: '/schema/',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutSchemaTableRoute =
  PathlessLayoutSchemaTableRouteImport.update({
    id: '/schema/$table',
    path: '/schema/$table',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutTableIndexRoute =
  PathlessLayoutTableIndexRouteImport.update({
    id: '/table/',
    path: '/table/',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutTableTableRoute =
  PathlessLayoutTableTableRouteImport.update({
    id: '/table/$table',
    path: '/table/$table',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PathlessLayoutIndexRoute
  '/browser': typeof PathlessLayoutBrowserRoute
  '/indexes': typeof PathlessLayoutIndexesRoute
  '/logs': typeof PathlessLayoutLogsRoute
  '/visualizer': typeof PathlessLayoutVisualizerRoute
  '/runner/$queryId': typeof PathlessLayoutRunnerQueryIdRoute
  '/schema/$table': typeof PathlessLayoutSchemaTableRoute
  '/table/$table': typeof PathlessLayoutTableTableRoute
  '/runner/': typeof PathlessLayoutRunnerIndexRoute
  '/schema/': typeof PathlessLayoutSchemaIndexRoute
  '/table/': typeof PathlessLayoutTableIndexRoute
}
export interface FileRoutesByTo {
  '/browser': typeof PathlessLayoutBrowserRoute
  '/indexes': typeof PathlessLayoutIndexesRoute
  '/logs': typeof PathlessLayoutLogsRoute
  '/visualizer': typeof PathlessLayoutVisualizerRoute
  '/': typeof PathlessLayoutIndexRoute
  '/runner/$queryId': typeof PathlessLayoutRunnerQueryIdRoute
  '/schema/$table': typeof PathlessLayoutSchemaTableRoute
  '/table/$table': typeof PathlessLayoutTableTableRoute
  '/runner': typeof PathlessLayoutRunnerIndexRoute
  '/schema': typeof PathlessLayoutSchemaIndexRoute
  '/table': typeof PathlessLayoutTableIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/_pathlessLayout/browser': typeof PathlessLayoutBrowserRoute
  '/_pathlessLayout/indexes': typeof PathlessLayoutIndexesRoute
  '/_pathlessLayout/logs': typeof PathlessLayoutLogsRoute
  '/_pathlessLayout/visualizer': typeof PathlessLayoutVisualizerRoute
  '/_pathlessLayout/': typeof PathlessLayoutIndexRoute
  '/_pathlessLayout/runner/$queryId': typeof PathlessLayoutRunnerQueryIdRoute
  '/_pathlessLayout/schema/$table': typeof PathlessLayoutSchemaTableRoute
  '/_pathlessLayout/table/$table': typeof PathlessLayoutTableTableRoute
  '/_pathlessLayout/runner/': typeof PathlessLayoutRunnerIndexRoute
  '/_pathlessLayout/schema/': typeof PathlessLayoutSchemaIndexRoute
  '/_pathlessLayout/table/': typeof PathlessLayoutTableIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browser'
    | '/indexes'
    | '/logs'
    | '/visualizer'
    | '/runner/$queryId'
    | '/schema/$table'
    | '/table/$table'
    | '/runner/'
    | '/schema/'
    | '/table/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/browser'
    | '/indexes'
    | '/logs'
    | '/visualizer'
    | '/'
    | '/runner/$queryId'
    | '/schema/$table'
    | '/table/$table'
    | '/runner'
    | '/schema'
    | '/table'
  id:
    | '__root__'
    | '/_pathlessLayout'
    | '/_pathlessLayout/browser'
    | '/_pathlessLayout/indexes'
    | '/_pathlessLayout/logs'
    | '/_pathlessLayout/visualizer'
    | '/_pathlessLayout/'
    | '/_pathlessLayout/runner/$queryId'
    | '/_pathlessLayout/schema/$table'
    | '/_pathlessLayout/table/$table'
    | '/_pathlessLayout/runner/'
    | '/_pathlessLayout/schema/'
    | '/_pathlessLayout/table/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/': {
      id: '/_pathlessLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutIndexRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/browser': {
      id: '/_pathlessLayout/browser'
      path: '/browser'
      fullPath: '/browser'
      preLoaderRoute: typeof PathlessLayoutBrowserRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/indexes': {
      id: '/_pathlessLayout/indexes'
      path: '/indexes'
      fullPath: '/indexes'
      preLoaderRoute: typeof PathlessLayoutIndexesRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/logs': {
      id: '/_pathlessLayout/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof PathlessLayoutLogsRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/visualizer': {
      id: '/_pathlessLayout/visualizer'
      path: '/visualizer'
      fullPath: '/visualizer'
      preLoaderRoute: typeof PathlessLayoutVisualizerRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/runner/': {
      id: '/_pathlessLayout/runner/'
      path: '/runner'
      fullPath: '/runner/'
      preLoaderRoute: typeof PathlessLayoutRunnerIndexRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/runner/$queryId': {
      id: '/_pathlessLayout/runner/$queryId'
      path: '/runner/$queryId'
      fullPath: '/runner/$queryId'
      preLoaderRoute: typeof PathlessLayoutRunnerQueryIdRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/schema/': {
      id: '/_pathlessLayout/schema/'
      path: '/schema'
      fullPath: '/schema/'
      preLoaderRoute: typeof PathlessLayoutSchemaIndexRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/schema/$table': {
      id: '/_pathlessLayout/schema/$table'
      path: '/schema/$table'
      fullPath: '/schema/$table'
      preLoaderRoute: typeof PathlessLayoutSchemaTableRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/table/': {
      id: '/_pathlessLayout/table/'
      path: '/table'
      fullPath: '/table/'
      preLoaderRoute: typeof PathlessLayoutTableIndexRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/table/$table': {
      id: '/_pathlessLayout/table/$table'
      path: '/table/$table'
      fullPath: '/table/$table'
      preLoaderRoute: typeof PathlessLayoutTableTableRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
  }
}

interface PathlessLayoutRouteChildren {
  PathlessLayoutBrowserRoute: typeof PathlessLayoutBrowserRoute
  PathlessLayoutIndexesRoute: typeof PathlessLayoutIndexesRoute
  PathlessLayoutLogsRoute: typeof PathlessLayoutLogsRoute
  PathlessLayoutVisualizerRoute: typeof PathlessLayoutVisualizerRoute
  PathlessLayoutIndexRoute: typeof PathlessLayoutIndexRoute
  PathlessLayoutRunnerQueryIdRoute: typeof PathlessLayoutRunnerQueryIdRoute
  PathlessLayoutSchemaTableRoute: typeof PathlessLayoutSchemaTableRoute
  PathlessLayoutTableTableRoute: typeof PathlessLayoutTableTableRoute
  PathlessLayoutRunnerIndexRoute: typeof PathlessLayoutRunnerIndexRoute
  PathlessLayoutSchemaIndexRoute: typeof PathlessLayoutSchemaIndexRoute
  PathlessLayoutTableIndexRoute: typeof PathlessLayoutTableIndexRoute
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutBrowserRoute: PathlessLayoutBrowserRoute,
  PathlessLayoutIndexesRoute: PathlessLayoutIndexesRoute,
  PathlessLayoutLogsRoute: PathlessLayoutLogsRoute,
  PathlessLayoutVisualizerRoute: PathlessLayoutVisualizerRoute,
  PathlessLayoutIndexRoute: PathlessLayoutIndexRoute,
  PathlessLayoutRunnerQueryIdRoute: PathlessLayoutRunnerQueryIdRoute,
  PathlessLayoutSchemaTableRoute: PathlessLayoutSchemaTableRoute,
  PathlessLayoutTableTableRoute: PathlessLayoutTableTableRoute,
  PathlessLayoutRunnerIndexRoute: PathlessLayoutRunnerIndexRoute,
  PathlessLayoutSchemaIndexRoute: PathlessLayoutSchemaIndexRoute,
  PathlessLayoutTableIndexRoute: PathlessLayoutTableIndexRoute,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
