/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as mainPathlessLayoutRouteImport } from './routes/(main)/_pathlessLayout'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as mainPathlessLayoutIndexRouteImport } from './routes/(main)/_pathlessLayout/index'
import { Route as mainPathlessLayoutChangelogRouteImport } from './routes/(main)/_pathlessLayout/changelog'
import { Route as mainPathlessLayoutRoadmapRouteImport } from './routes/(main)/_pathlessLayout/roadmap'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const mainPathlessLayoutRoute = mainPathlessLayoutRouteImport.update({
  id: '/(main)/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const mainPathlessLayoutIndexRoute = mainPathlessLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainPathlessLayoutRoute,
} as any)
const mainPathlessLayoutChangelogRoute =
  mainPathlessLayoutChangelogRouteImport.update({
    id: '/changelog',
    path: '/changelog',
    getParentRoute: () => mainPathlessLayoutRoute,
  } as any)
const mainPathlessLayoutRoadmapRoute =
  mainPathlessLayoutRoadmapRouteImport.update({
    id: '/roadmap',
    path: '/roadmap',
    getParentRoute: () => mainPathlessLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/changelog': typeof mainPathlessLayoutChangelogRoute
  '/roadmap': typeof mainPathlessLayoutRoadmapRoute
  '/': typeof mainPathlessLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/changelog': typeof mainPathlessLayoutChangelogRoute
  '/roadmap': typeof mainPathlessLayoutRoadmapRoute
  '/': typeof mainPathlessLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRoute
  '/(main)/_pathlessLayout': typeof mainPathlessLayoutRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/(main)/_pathlessLayout/changelog': typeof mainPathlessLayoutChangelogRoute
  '/(main)/_pathlessLayout/roadmap': typeof mainPathlessLayoutRoadmapRoute
  '/(main)/_pathlessLayout/': typeof mainPathlessLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/api/search'
    | '/docs/$'
    | '/changelog'
    | '/roadmap'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/admin' | '/api/search' | '/docs/$' | '/changelog' | '/roadmap' | '/'
  id:
    | '__root__'
    | '/admin'
    | '/(main)/_pathlessLayout'
    | '/api/search'
    | '/docs/$'
    | '/(main)/_pathlessLayout/changelog'
    | '/(main)/_pathlessLayout/roadmap'
    | '/(main)/_pathlessLayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRoute
  mainPathlessLayoutRoute: typeof mainPathlessLayoutRouteWithChildren
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/_pathlessLayout': {
      id: '/(main)/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainPathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/_pathlessLayout/': {
      id: '/(main)/_pathlessLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainPathlessLayoutIndexRouteImport
      parentRoute: typeof mainPathlessLayoutRoute
    }
    '/(main)/_pathlessLayout/changelog': {
      id: '/(main)/_pathlessLayout/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof mainPathlessLayoutChangelogRouteImport
      parentRoute: typeof mainPathlessLayoutRoute
    }
    '/(main)/_pathlessLayout/roadmap': {
      id: '/(main)/_pathlessLayout/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof mainPathlessLayoutRoadmapRouteImport
      parentRoute: typeof mainPathlessLayoutRoute
    }
  }
}

interface mainPathlessLayoutRouteChildren {
  mainPathlessLayoutChangelogRoute: typeof mainPathlessLayoutChangelogRoute
  mainPathlessLayoutRoadmapRoute: typeof mainPathlessLayoutRoadmapRoute
  mainPathlessLayoutIndexRoute: typeof mainPathlessLayoutIndexRoute
}

const mainPathlessLayoutRouteChildren: mainPathlessLayoutRouteChildren = {
  mainPathlessLayoutChangelogRoute: mainPathlessLayoutChangelogRoute,
  mainPathlessLayoutRoadmapRoute: mainPathlessLayoutRoadmapRoute,
  mainPathlessLayoutIndexRoute: mainPathlessLayoutIndexRoute,
}

const mainPathlessLayoutRouteWithChildren =
  mainPathlessLayoutRoute._addFileChildren(mainPathlessLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRoute,
  mainPathlessLayoutRoute: mainPathlessLayoutRouteWithChildren,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
